name: functional-itertools

dependencies:
  - python=3.7.*

  - attrs >= 19.3
  - more-itertools >= 8.2

  # testing
  - hypothesis
  - pytest
  - pytest-cov
  - pytest-xdist = 1.29

  # publishing
  - pre-commit
  - twine
  - versioneer

  # pip
  - pip
  - pip:
      - pytest-randomly
